
spring:
  profiles:
    actvive: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/batch
      username: sa
      password:
      driver-class-name: org.h2.Driver
#  batch:
#    jdbc:
#      initialize-schema: embedded

---
spring:
  config:
    activate:
      on-profile: sqlserver
  datasource:
    hikari:
#      jdbc-url: jdbc:sqlserver://localhost;databaseName=springbatch;integratedSecurity=true;encrypt=true;trustServerCertificate=false;trustStore= C:\Program Files\Java\jdk-14.0.2\lib\cacert;trustStorePassword=changeit
      jdbc-url: jdbc:sqlserver://localhost;databaseName=springbatch;trustServerCertificate=true
      username: sa
      password: localtest
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always

    job:
      names: ${job.name:NONE}
#      enabled: false #자동실행 방지